name: Check that server builds successfully

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Install opam
      run: sudo apt-get install -y libev-dev opam
    
    - name: Opam init
      run: opam init --bare

    - name: Install Ocaml 4.14.0
      run: opam switch create 4.14.0

    - name: Install opam dependencies
      run: opam install -y . --deps-only 

    - name: Build server
      run: |
        eval $(opam env)
        dune build src/main.exe